sudo: false

language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file conda_requirements.txt
  - pip install -r test_requirements.txt
  - pip install -r pip_requirements.txt
  - python setup.py install

script:
  - ./bin/test pep8 cov

after_success:
  - codecov

notifications:
  email: false
