on: push
  push:
    tags:
      - 'v*'

name: Create release notes

jobs:
  build:
    name: Release notes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0  # to retrieve entire history of refs/tags

      - name: Generate release notes
        run: |
          git fetch --all --tags
          chmod +x .github/workflows/logger.sh
          bash .github/workflows/logger.sh
          echo ::set-env name=TAG::$(git tag | sort -V | tail -1)

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          create_draft: true
          created_tag: ${{ env.TAG }}
          update_existing: false
          release_title: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
